export const AD_ACCOUNT_LIST_PROJECTION = {
  _id: 1,
  uid: 1,
  email: 1,
  name: 1,
  accountId: 1,
  metaAccountId: 1,
  metaAccountName: 1,
  currency: 1,
  spendCap: 1,
  budget: 1,
  spent: 1,
  status: 1,
  balance: 1,
  assignedBy: 1,
  assignedAt: 1,
  unassignedAt: 1,
  lastSyncedAt: 1,
  syncStatus: 1,
  syncError: 1,
  createdAt: 1,
  updatedAt: 1,
};

export const USER_AD_ACCOUNT_PROJECTION = {
  _id: 1,
  uid: 1,
  email: 1,
  name: 1,
  accountId: 1,
  metaAccountId: 1,
  metaAccountName: 1,
  currency: 1,
  spendCap: 1,
  spent: 1,
  status: 1,
  createdAt: 1,
  lastSyncedAt: 1,
  lastInsights: 1,
};

export const USER_PROJECTION = {
  _id: 1,
  uid: 1,
  email: 1,
  displayName: 1,
  phoneNumber: 1,
  role: 1,
  accountStatus: 1,
  accountType: 1,
  isDemoAccount: 1,
  dollarRate: 1,
  availableBalance: 1,
  totalEarned: 1,
  createdAt: 1,
};

export const DEPOSIT_LIST_PROJECTION = {
  _id: 1,
  uid: 1,
  email: 1,
  amount: 1,
  amountBDT: 1,
  account: 1,
  transactionRef: 1,
  creditedUSD: 1,
  paymentMethod: 1,
  status: 1,
  reason: 1,
  createdAt: 1,
  updatedAt: 1,
};

export const META_AD_ACCOUNT_PROJECTION = {
  _id: 1,
  metaAccountId: 1,
  name: 1,
  currency: 1,
  balance: 1,
  spendCap: 1,
  amountSpent: 1,
  accountStatus: 1,
  disableReason: 1,
  importedAt: 1,
};
